modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "icon.png"
logoBlur = false
description = "${description}"
authors = "${mod_author}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.corpse.mixins.json"

[[dependencies."${mod_id}"]]
modId = "sable_player_ragdoll"
type = "required"
versionRange = "[0.7.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ragdoll_corpse"
type = "optional"
versionRange = "[0.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"
